Split cross-reference processing from link processing
dictionaria/pydictionaria pull request #18
Opened 2019-06-03 08:08 UTC by johenglisch

Problem: Processing cross-references is cumbersome:

 * Processing cross-references required the `md.json` to specify a regex
 * The link processing code created a markdown-style link -- and then stripped the markdown afterwards
 * Cross-references were just hard-coded

Some changes to link processing to make things easier:

 * Moved cross-reference processing out of link processing
 * Create separate JSON property `cross_references` (`\cf`, `\mn`, etc. are pre-defined)
 * Renamed some of the properties to make their function more clear (hopefully)

Changes for the `md.json`:
 1. `references` → `sources`
 2. `links_with_no_label` →  `cross_references`
 3. `process_links_in_labels` → `process_links_in_markers`
 4. `link_display_label` → `link_label_marker´
 5. `entry_label_as_regex_for_link` → `link_regex`

2019-06-03 15:20 UTC, xrotwang requested changes
I like the general direction, but would really prefer to keep "references" over "sources". A reference is some information which makes looking up sources possible.

2019-06-03 16:47 UTC, johenglisch commented
Hm, I see what you mean.  My reasoning was that having two properties with similar names like `references` and `cross_references` might be confusing (and prone to errors).

2019-06-03 17:17 UTC, xrotwang commented
Ah, ok. This makes sense, too. Also, the CLDF property holding references
is called source. So ... I guess I'm ok with this 😀

Johannes Englisch <notifications@github.com> schrieb am Mo., 3. Juni 2019,
18:47:

> Hm, I see what you mean. My reasoning was that having two properties with
> similar names like references and cross_references might be confusing
> (and prone to errors).
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/dictionaria/pydictionaria/pull/18?email_source=notifications&email_token=AAGUOKBKAFVZ3TVPMB7QFGLPYVDLTA5CNFSM4HSFS4DKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW2AFKA#issuecomment-498336424>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAGUOKEEOK77WD3N3RSNF6DPYVDLTANCNFSM4HSFS4DA>
> .
>

2019-06-04 06:20 UTC, xrotwang approved these changes
I guess, I'm ok with this after all. There's no change in the CLDF which is produced, correct?

2019-06-04 06:21 UTC, merged